window.NUMO_BUTTON_TEXT = {
  refreshButton: "Refresh Stock",
  orderButton: "DAPATKAN AKAUN",
  loginButton: "LOGIN",
  logoutButton: "LOGOUT",
  topupButton: "TOPUP KREDIT / CONTACT ADMIN",
  passwordPlaceholder: "Password reseller",
  checkingPasswordText: "Checking password...",
  wrongPasswordText: "Password salah / akaun tidak aktif. Sila cuba semula.",
  loginSuccessText: "Login berjaya.",
  priceHeaderPlan: "Plan",
  priceHeaderReseller: "Reseller",
  priceHeaderSell: "Jual Min",
  noPriceText: "Harga belum tersedia. Sila tanya admin.",
  slotText: "slot available",
  loadingText: "Loading stock...",
  noDataText: "Tiada data stock.",
  errorText: "Gagal load stock.<br />Sila refresh semula atau hubungi admin.",
  lastUpdatedText: "Last updated:"
};
